### PR TITLE
[WIP] Adding Docker support

### PR DESCRIPTION
**Pull request by robert-wagner**
This is a work in progress adding docker support for grid worker

### CODE REVIEW

**Comment by robert-wagner** [comment]
#16

**Comment by ppirrip** [comment]
I am looking for a docker image myself so I don't have to contaminate my box and deal with venv, so I can do a test run and I learn more about this sw

**Comment by jvmancuso** [comment]
@ppirrip if you're into it, I'm sure @robert-wagner would be willing to hand over the reigns.  I think he's been working on MPC stuff lately so hasn't had a chance to get back to this yet.

**Comment by ppirrip** [comment]
I can take a look, as I am building a vanilla dirty-hack ubuntu 16.04 image for Grid testing, but I don't have access to GPU (all I have is google colab), that acceptance requirement for TF/keras/Torch out of the box I can't really test. Anyway, I will play around and ask for help when I am stuck.

**Pull request closed without merging**
