### PR TITLE
Add list of bootstrap IPFS nodes

### PR DESCRIPTION
**Pull request by adamrainsby**
To make it quicker to discover OpenMined workers

### CODE REVIEW

**Comment by justin1121** [comment]
Hey, this is a great idea. I just don't think we can merge this until we understand the consequences of adding to the list. See here: https://ipfs.io/docs/commands/#ipfs-bootstrap-add And once understand the consequences I think we need to add trusted nodes in a way that the majority of people using the Grid agree with. Could be some major security holes here.

**Comment by adamrainsby** [comment]
@justin1121 You're right to be cautious.

The security implications as far as I understand are if you add untrusted peers they could introduce you to only malicious peers. So the nodes in the list need to be ones we can trust/control.

> I think we need to add trusted nodes in a way that the majority of people using the Grid agree with

Yep

**Comment by jvmancuso** [comment]
Once we have a reputation system up and running, that could be a good heuristic for measuring trust.  Until then, we might want to add some AWS free tier bootstrap nodes that the core developers are in control of (mainly to aid development and to make sure this actually improves performance). We'd just have to monitor edits to this list pretty carefully in the meantime.

**Comment by iamtrask** [comment]
This is an awesome PR! - I think that perhaps we should move the specific list to a separate repo that has more restrictive push access permissions - which I will take care of shortly. Great work Adam!

**Comment by justin1121** [comment]
@adamrainsby yeah I haven't looked into the actual security implications much I was mostly just scared by the warning messages on the docs I mentioned. But avoiding linking to malicious peers sounds like something we should avoid.

Also I was doing some testing and when I added a bootstrap peer in the p2p-circuit format it still took just as long to connect to that node. I think you need to actual supply an IP address/domain name to connect directly to the bootstrap nodes. If you just supply a p2p-circuit or  just an ipfs address it still needs to go through other nodes to find that node. IP Address format like this `/ip4/192.168.2.18/tcp/4001/ipfs/<ipfs address>`. So whoever starts up nodes needs to be comfortable with sharing their public IP address and probably make sure the machines that want to be bootstrap nodes are either locked down in a security sense properly or make sure that being a bootstrap node is their only purpose.

**Comment by justin1121** [comment]
@adamrainsby if you want to remove your IPFS address from this commit we can merge this and then @iamtrask will create a new repo with the bootstrap IPFS addresses.

**Comment by iamtrask** [comment]
New repo created - https://github.com/OpenMined/BootstrapNodes

**Comment by iamtrask** [comment]
Gonna close this here since we're adding the list to a separate Repo - Adam, since this was originally your work I'd love for you to submit a PR with your request to the other repository so we have a paper trail :)

**Comment by adamrainsby** [comment]
@iamtrask Cool. I'll open a PR in the new repo later when I get home.

**Pull request closed without merging**
