### PR TITLE
Heroku script for creating app instance

### PR DESCRIPTION
**Pull request by hanare**
Bash script to create Heroku instance for rest_api app or websocket based on the flags used.
Allows to you link existing Redis cloud instance using the global name or create a new one.

### CODE REVIEW

**Comment by jlebensold** [comment]
Hi @hanare thanks for this. How does this improve the current script?

**Comment by hanare** [comment]
@jlebensold 
1)the current script doesn't allow user to specify which app to needs to be deployed to heroku 
2) It directly creates a new redis instance, instead we can reuse the existing instance if any
3) deployment Of rest_api and websocket can be configured based on flags

**Comment by hanare** [comment]
Hi @jlebensold 
1)the current script doesn't allow user to specify which app to needs to be deployed to heroku 
2) It directly creates a new redis instance, instead we can reuse the existing instance if any
3) deployment Of rest_api and websocket can be configured based on flags

**Comment by mari-linhares** [comment]
Thanks for the contribution @hanare!

**Pull request merged**
